variable "vpc" {}
variable "env" {}
variable "app" {}
variable "bastion_cidr" {}
variable "default_vpc_id" {}
variable "default_vpc_cidr" {}
variable "default_vpc_rtb" {}
variable "engine_version" {}
variable "docdb" {}
variable "kms_arn" {}