variable "vpc" {}
variable "env" {}
variable "app" {}
variable "bastion_cidr" {}
variable "default_vpc_id" {}
variable "default_vpc_cidr" {}
variable "default_vpc_rtb" {}
variable "docdb" {}
variable "kms_arn" {}
variable "rds" {}
variable "elasticache" {}
variable "rabbitmq" {}
variable "instance_type" {}